const bikesData = [
  {
    id: 1,
    name: "Yamaha R15",
    price: 160000,
    engine: "155cc",
    mileage: "45 kmpl",
    category: "Sport",
    brand: "Yamaha",
    topSpeed: "136 kmph",
    fuelCapacity: "11L",
  },
  {
    id: 2,
    name: "KTM Duke 200",
    price: 190000,
    engine: "199cc",
    mileage: "35 kmpl",
    category: "Naked",
    brand: "KTM",
    topSpeed: "140 kmph",
    fuelCapacity: "13.5L",
  },
  {
    id: 3,
    name: "Royal Enfield Classic 350",
    price: 210000,
    engine: "349cc",
    mileage: "37 kmpl",
    category: "Cruiser",
    brand: "Royal Enfield",
    topSpeed: "114 kmph",
    fuelCapacity: "13L",
  },
  {
    id: 4,
    name: "Honda Hornet 2.0",
    price: 140000,
    engine: "184cc",
    mileage: "42 kmpl",
    category: "Naked",
    brand: "Honda",
    topSpeed: "127 kmph",
    fuelCapacity: "12L",
  },
  {
    id: 5,
    name: "Bajaj Pulsar NS200",
    price: 150000,
    engine: "199cc",
    mileage: "40 kmpl",
    category: "Sport",
    brand: "Bajaj",
    topSpeed: "135 kmph",
    fuelCapacity: "12L",
  },
  {
    id: 6,
    name: "Suzuki Gixxer SF",
    price: 130000,
    engine: "155cc",
    mileage: "46 kmpl",
    category: "Sport",
    brand: "Suzuki",
    topSpeed: "135 kmph",
    fuelCapacity: "12L",
  },
  {
    id: 7,
    name: "TVS Apache RR310",
    price: 260000,
    engine: "312cc",
    mileage: "34 kmpl",
    category: "Sport",
    brand: "TVS",
    topSpeed: "165 kmph",
    fuelCapacity: "11L",
  },
  {
    id: 8,
    name: "Hero Xtreme 160R",
    price: 125000,
    engine: "163cc",
    mileage: "50 kmpl",
    category: "Sport",
    brand: "Hero",
    topSpeed: "114 kmph",
    fuelCapacity: "12L",
  },
  {
    id: 9,
    name: "Yamaha MT-15",
    price: 170000,
    engine: "155cc",
    mileage: "45 kmpl",
    category: "Naked",
    brand: "Yamaha",
    topSpeed: "131 kmph",
    fuelCapacity: "10L",
  },
  {
    id: 10,
    name: "Honda CB350",
    price: 200000,
    engine: "348cc",
    mileage: "35 kmpl",
    category: "Cruiser",
    brand: "Honda",
    topSpeed: "143 kmph",
    fuelCapacity: "15L",
  },
  {
    id: 11,
    name: "Bajaj Dominar 400",
    price: 230000,
    engine: "373cc",
    mileage: "30 kmpl",
    category: "Touring",
    brand: "Bajaj",
    topSpeed: "156 kmph",
    fuelCapacity: "13L",
  },
  {
    id: 12,
    name: "Royal Enfield Himalayan",
    price: 280000,
    engine: "411cc",
    mileage: "30 kmpl",
    category: "Adventure",
    brand: "Royal Enfield",
    topSpeed: "127 kmph",
    fuelCapacity: "15L",
  },
  {
    id: 13,
    name: "KTM RC 200",
    price: 220000,
    engine: "199cc",
    mileage: "34 kmpl",
    category: "Sport",
    brand: "KTM",
    topSpeed: "140 kmph",
    fuelCapacity: "10L",
  },
  {
    id: 14,
    name: "Hero Splendor Plus",
    price: 85000,
    engine: "97cc",
    mileage: "65 kmpl",
    category: "Commuter",
    brand: "Hero",
    topSpeed: "82 kmph",
    fuelCapacity: "9.8L",
  },
  {
    id: 15,
    name: "Honda Shine",
    price: 95000,
    engine: "124cc",
    mileage: "60 kmpl",
    category: "Commuter",
    brand: "Honda",
    topSpeed: "100 kmph",
    fuelCapacity: "10.5L",
  },
  {
    id: 16,
    name: "TVS Raider 125",
    price: 95000,
    engine: "124cc",
    mileage: "57 kmpl",
    category: "Commuter",
    brand: "TVS",
    topSpeed: "99 kmph",
    fuelCapacity: "10L",
  },
  {
    id: 17,
    name: "Yamaha FZ V3",
    price: 120000,
    engine: "149cc",
    mileage: "48 kmpl",
    category: "Naked",
    brand: "Yamaha",
    topSpeed: "110 kmph",
    fuelCapacity: "13L",
  },
  {
    id: 18,
    name: "Suzuki Access 125",
    price: 90000,
    engine: "124cc",
    mileage: "50 kmpl",
    category: "Scooter",
    brand: "Suzuki",
    topSpeed: "85 kmph",
    fuelCapacity: "5.6L",
  },
];
export default bikesData;
