import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { ThemeProvider } from "@/context/themeProvider";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/layout/navBar";
import Footer from "@/components/layout/footer";
import { Toaster } from "@/components/ui/sonner";
import { FavoritesProvider } from "@/context/favoriteCount";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bike rentals",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/logo-dark.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <FavoritesProvider>
            <Navbar />
            {/* <main className="mt-16"> {children}</main> */}
            <main className="main-content home-body mt-18">{children}</main>
            <Toaster />
            <Footer />
          </FavoritesProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
